### ISSUE TITLE
Make all strings properly translateable

### ISSUE THREAD

**Issue by mintplugins** [RebelCodecom/edd-bookings#4]
Every string should be translate-able by using WordPress's translation functions. 

For example, this error message is not translate-able. It should be made so by WordPress translation standards:

```
"Plugin dependencies are not installed!<br/>"
        . "Please run <code>composer install</code> at directory <code>%s</code><br/>"
        . "The EDD Bookings plugin will be deactivated."
```

The above should be something more like this (though not exactly this):
```
__( "Plugin dependencies are not installed!", 'eddbk' );
__( "Please run", 'eddbk' ) . ' <code>composer install</code> ' . __( 'at directory', 'eddbk' ) . sprintf( ' <code>%s</code><br /> ', EDD_BK_DIR ) . __( "The EDD Bookings plugin will be deactivated", 'eddbk' ) . '.';
     
```

Notice how anything that is translateable is separated out into its own translation wrapper to make it easy for anyone to translate. 

I have noticed these untranslate-able strings all through the plugin. Some are wrapped in translation function wrappers but incorrectly. For example, this one does not use a correct translation string:

```
$message = sprintf(
                __('Your chosen "%s" session on %s is no longer available. It may have been booked by someone else. If you believe this is a mistake, please contact the site administrator.',
                    'eddk'), get_the_title($item['id']), $dateTimeStr
            );
```

I don't have time to go through every line but this is a WordPress standard that really should be followed for all extensions.

See translation functions from WordPress codex:
https://codex.wordpress.org/Function_Reference/_2

**Comment by mecha** [comment]
Thanks @mintplugins!

We didn't bother with that first message regarding the Composer install-able dependencies since that message will never be shown on customers' sites. It's only there for us developers to remind us that dependencies are missing. But I suppose it wouldn't hurt to make it translatable either.

Regarding the latter, what exactly is un-translatable about using `sprintf()` with `__()`? The only thing that could be improvement imo is to number the placeholders as `"%1$s"`, `"%2$s"`, etc. Or is it something else, like say the division of the string into sentences?

**Comment by mintplugins** [comment]
You shouldn't use sprint_f inside a translation string because it is using a code equivalent of language at that point with the %s variables. 

%s is not an actual word in any language so it shouldn't be wrapped in a translation function. 

For example, if someone was translating that string to French, they would have to put the %s back into the french string in their poedit file - even though %s is not a French word. This is confusing for the user and also allows for the possibility of it breaking upon translation - as they could just leave it out of their translation string - and now the sprint_f function doesn't have an %s to replace.

Just in case you are unfamiliar, here's an example of a translation taking place in poedit and the %s causing confusion (this is using your poedit file in bookings).

<img width="762" alt="screen shot 2016-11-02 at 10 47 00 am" src="https://cloud.githubusercontent.com/assets/1638128/19933519/0170fa84-a0ea-11e6-81d2-1d50b9cd515a.png">

Also, in that last example, your translation string is not correct. It should be "eddbk" to match your plugin's translation string. Currently, it is set to "eddk" but it should be "eddbk". 

I recommend that you go through all of your translations to make sure they are set correctly everywhere. I have only checked 2 places because of time constraints. However, this needs to be checked and fixed plugin-wide with every single string - whether it's just for developers or whether it is for front-facing users. This is just a standard that has to be followed for all strings in WordPress plugins and themes.

**Comment by XedinUnknown** [comment]
Using string formatting is *the* way to localize strings. It is done specifically so that the string retains its inherent context, while allowing _variable_ values to be inserted. The translators are aware of this methodology (and if not, why aren't they?), which gives them the way to place the variable values in any place of the string, instead of a position fixed by the software developer.
Additionally, string formatting does not contradict the [WordPress localization guidelines](https://codex.wordpress.org/I18n_for_WordPress_Developers); on the contrary, it is in accord with them.

@mecha, in my opinion, string formatting should be used for localization here and wherever possible. At the same time, I highly recommend adding numbers to the placeholders. Not doing so may prevent some strings from being correctly translatable in some languages, as the position of variables may change to conform to the grammar of that language..

**Comment by XedinUnknown** [comment]
@mecha, if you feel that the formatting of the string may cause confusion among the translators, please consider using [`_x()`](https://codex.wordpress.org/Function_Reference/_x) for that string.

**Comment by mecha** [comment]
@mintplugins Otto, which I'm told is somewhat of a guru on translations, [says it's the way to go](http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/). See the **Annoyance the First** section further down the page.

As @XedinUnknown pointed out, if a string where to be split, for example:

`__('You chosen ') . $download . __(' session on ') . $date . __(' is not available').`

then translations are forced to use that sentence structure. A language might not follow such sentence structure and might require the words to be reordered. In other cases, each fragment might not be literally translated, even if the order remains the same. For instance, in Maltese the above example would translate to
`__('Is-sessjoni li ghazilt ghal') . $download . __('ghad-data') . $data . __('mihiex disponibbli')`

The order is the same, but each Maltese fragment does not translate to the corresponding English fragment. The middle English fragment *"session on"* is replaced with a Maltese fragment that means *"for the date"*. This is of course only an example since in reality, the translator would need to provide and **invalid** phrase translation to achieve a **valid** sentence translation. Or not even be capable of translating such a short sentence fragment.

@XedinUnknown Yes, `_x()` is great for specifying context. However that only solves the problem of having sentence fragments not having any context. The fact that their order and grouping is given explicitly and cannot be changed by translators is still a problem.

I see nothing wrong with having placeholders in translation string. I think translators should be aware of what placeholders represent. It allows the string to remain a single whole piece while also containing a means of injecting values later on - the order of which can change.

**Comment by XedinUnknown** [comment]
@mecha, I meant that if the translator is unsure what the `%s` stands for, the developer can give meaning to it in the context string.

**Comment by mecha** [comment]
@XedinUnknown Ah! That's brilliant. You mean something like the following, correct?

`__('%d errors', '%d is the number of errors')`

**Comment by XedinUnknown** [comment]
@mecha, exactly.

**Comment by XedinUnknown** [comment]
@mecha, or perhaps, do be more in line with the typical usage examples, you could provide an example of a complete string, with the placeholders replaced.

**Comment by mecha** [comment]
@XedinUnknown You mean like the following?

```php
sprintf(
    _x(
        'To create a bookable service go to %1$s and tick the %2$s option.',
        'To create a bookable service go to "Downloads > Add New" and tick the "Enable Bookings" option.',
        'eddbk'
    ),
    $addDownloadPageNavigationLink,
    $enableBookingsOptionLabel
);
```

**Comment by XedinUnknown** [comment]
@mecha, that looks good. All the context you will ever need, with an example of value and correct placement. Eventually, the context string appears to look like what @mintplugins seems to want the translation string to be. I think this is the best way to make everyone happy.

**Comment by mecha** [comment]
I like it. @mintplugins Any thoughts?

**Comment by XedinUnknown** [comment]
@mecha, one remark on the above, however. In the particular case of your previous example, maybe it's best to have the "Downloads > Add New" and "Enable Bookings" in the translation string directly, unless they are translated elsewhere, because they need to be translated too.

**Comment by mintplugins** [comment]
That is definitely better (using _x with context).

The issue I often see is that translators are not professionals. In a perfect world, everyone translating things is a professional translator - but there isn't a lot of money in it so most site owners translate their own by themselves with no training (which is usually why they don't know what %s means or other translation methodology @XedinUnknown). Making it as simple as possible for the non-professional actually makes it work better in a real-world scenario.

**Comment by mintplugins** [comment]
I would even recommend choosing your phrasing accordingly to eliminate the needs for %s in the middle of your phrases as often. Something like this change:

Before:
__( "Please run", 'eddbk' ) . ' <code>composer install</code> ' . __( 'at directory', 'eddbk' ) . sprintf( ' <code>%s</code><br /> ', EDD_BK_DIR ) . __( "The EDD Bookings plugin will be deactivated", 'eddbk' ) . '.';

After:
__( "You need to run the following code to install composer", 'eddbk' ) . ': <code>composer install</code> ' . __( 'It needs to be run in the following directory', 'eddbk' ) . sprintf( ' <code>%s</code><br /> ', EDD_BK_DIR ) . __( "The EDD Bookings plugin will be deactivated", 'eddbk' ) . '.';

By changing how you phrase things, you've completely eliminated the need for a %s to be part of the string the user is translating. This won't always work, but choosing how things are phrased can often de-complicate things for the novice translator.

**Comment by mintplugins** [comment]
@XedinUnknown By the thumbs down what are you saying? Do you think that translating a string with a %s is easier for the average user and phrases should be constructed to include them whenever possible?

I think the context option is great - and if you can go even further and avoid the need for it in some situations, that is even better. That's just my 2 cents.

**Comment by mecha** [comment]
@mintplugins I understand your point. This is still however a debate about the level of compromise.

On the one hand we have string and translation maintainability, as well as natural language output. Some sentences will just look and feel odd if they are re-formatted to fit translations purposes.

On the other hand we have translator user-friendliness. Non-tech users will be confused with placeholders. Rethinking our sentences to eliminate the need for placeholders is also a good idea. 

Frankly, I don't see how the latter is a big problem. I understand that many users will attempt to make their own make-shift translations, but translating strings is not as easy as it is made to be. I can't phone my car manufacturer and complain about how a non-engineer like myself cannot modify anything in my car's engine because it's too complicated.

The "best" we can do is make the strings as easy as possible, where applicable, to translate but there's only so much simplification we can do before the plugin's text starts to feel babyish or too "computerized".

**Comment by mintplugins** [comment]
@mecha Definitely agree with everything you're saying there. 

I think one difference is that in this case, as opposed to the car manufacturer, we do get complaints like that all the time. :P

Regardless, the main idea is that we just do our best to make it easy and when we can't, we can't. Definitely love the use of _x with context in those cases.

**Comment by mecha** [comment]
@mintplugins Went through the plugin and made all the appropriate fixes we could find. Here are the changes if you want to review them:

Commit https://github.com/RebelCodecom/edd-bookings/commit/e4f5b01ed79629b080bca18e80cf0315646ff2f3

**Comment by XedinUnknown** [comment]
@mintplugins, what I meant is that I don't really care what the average user finds easier to do. Translations are not for everybody, and just like if you want to create a raster design you have to learn the basics of Photoshop, if a user wants to create a translation - they should first learn about the basics of localization and internationalization. There are professional tools that make the lives of professionals easier, and standards that these tools support. If we chase what an average user finds easier to understand - then we can never create any good tools. However, please note that I'm saying this because we are talking about plugin *development*. When it comes to actually *using* the plugin, then we must always try to do what is easier for the user. But in development, we do what is most efficient and convenient for developers. The users will never even see the dev side - translations in this case. And if they do - then they know what they're up for ;)

**Comment by mintplugins** [comment]
@mecha That is definitely a massive improvement. Thanks!

**Comment by mecha** [comment]
@mintplugins Great! Incorporated the changes into [v2.1.3-RC4](https://github.com/RebelCodecom/edd-bookings/releases/tag/v2.1.3-rc4).
