### ISSUE TITLE
Long delay when loading calendar

### ISSUE THREAD

**Issue by mecha** [RebelCodecom/edd-bookings#9]
A couple of users have reported that, after updating to `2.1.3`, the front-end calendar is experiencing a long delay before it appears and shows as loading.

After inspecting one of the affected sites I noticed that the AJAX requests that the JS sends to the server to retrieve the session picker markup and Download meta data are taking an unusually long time to complete. As of yet no cause has been found.

**Comment by mecha** [comment]
So I'm looking into possible optimizations and may have found a solution.

The Session Picker widget (aka the front-end calendar) is initialized by loading 3 child widgets: the date picker, time picker and duration picker. Their HTML content is retrieved via AJAX in that order - which matters!

The proposed optimization involves allowing the child widgets to be able to be loaded in parallel, rather than sequentially. Since this means 3 async AJAX requests, this should reduce the load time by 66%.

This will involve a lot of testing to determine if the child widgets can be loaded in this manner. During development it was determined that JS errors related to timing can occur.

**Comment by pippinsplugins** [comment]
I'm fairly certain there's more of an issue here. This site, for example, http://www.mmtarotreadings.com.au/sessions/tarot-card-reading-15-minutes/, takes nearly a minute to load the calendar. It didn't use to.

That site itself is pretty slow, but check out how much faster the EDD checkout screen is. If the delay was purely caused by the site's performance, EDD checkout would also be incredibly slow, but it's not.

**Comment by mecha** [comment]
@pippinsplugins After the recent updates the performance of the calendar should be much better. Have you continued to receive reports regarding this?

**Comment by pippinsplugins** [comment]
Glad to hear it! I have not seen any recent reports of it.
